w7d2/music/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :bands do
    resources :albums, only: [:new, :create] 
  end

  resources :tracks, except: [:index, :new]


  resources :albums, except: [:new, :create, :index] do
    resources :tracks, only: [:new, :create]
  end


  resources :users, only: [:new, :create, :show, :destroy] 
  resource :sessions, only: [:new, :create, :destroy]
end

w7d2/music/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year,  presence: true

  belongs_to :band, dependent: :destroy,
  foreign_key: :band_id,
  class_name: :Band

  has_many :tracks,
  foreign_key: :album_id,
  class_name: :Track


end

w7d2/music/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  foreign_key: :band_id,
  class_name: :Album

  has_many :tracks,
  through: :albums,
  source: :track

end

w7d2/music/app/models/track.rb
class Track < ApplicationRecord
  validates :album_id, :title, :ord, :track_type, presence: true

  belongs_to :album, dependent: :destroy,
  foreign_key: :album_id,
  class_name: :Album

end

w7d2/music/app/models/user.rb
class User < ApplicationRecord
  validates :email, uniqueness: true

  after_initialize :ensure_session_token
  attr_reader :password # to validate password length later

  # SPIRE self.find_by_credentials   is_password   password=() reset_session_token  ensure_session_token
  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)

       user
    else
       nil
    end
  end

  def self.generate_session_token
     SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

w7d2/music/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_band, only: [:create]

  def index
    @albums = Album.all

    render :index
  end

  def show
    @album = Album.find_by(id: params[:id])

    if @album
      render :show
    else
      redirect_to albums_url
    end
  end

  def new
    render :new
  end
  
  def create
    # new_params = album_params[:album][:band_id] = params[:band_id]
    # @album = Album.new(new_params)
    # @album = Album.new(new_params)
     @album = @band.albums.new(album_params)
    if @album.save!
      redirect_to album_url(@album)
    else
      render :new
    end
  end

  def destroy
    album = Album.find(id: params[:id])
    album.destroy
  end

  def update
    @album = Album.find(id: params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      render :edit
    end

  end

  def edit
    render :edit
  end

  private
  def set_band
    @band = Band.find(params[:band_id])
  end

  def album_params 
    params.require(:album).permit(:title, :year, :live)
  end

end

w7d2/music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    if logged_in?
      session[:session_token] = nil
      current_user.reset_session_token!
      @current_user = nil
    end
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def un_signed_in
    if logged_in?
      redirect_to user_url(current_user)
    end
  end
end

w7d2/music/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all

    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])
    if @band 
      render :show
    else
      redirect_to bands_url
    end
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def new
    render :new
  end

  def edit
      render :edit
  end

  def update
    @band =  Band.find_by(id: params[:id])
    if @band
      if @band.update(band_params)
        redirect_to band_url(@band)
      else
        render :edit
      end
    end
  end

  def destroy
    band = Band.find_by(id: params[:id])
    band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

w7d2/music/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_user_url
  end

  # sign in form
  def new
    render :new
  end
end

w7d2/music/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_album, only: [:create]

  def show
    @track = Track.find_by(id: params[:id])

    render :show
  end

  def create
    @track = @album.tracks.new(track_params)
    if @track.save!
      redirect_to track_url(@track)
    else
      render :new
    end 
  end

  def new
    render :new
  end

  def update
    @track = Track.find_by(id: params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      render :edit
    end
  end

  def edit
    @track = Track.find_by(id: params[:id])
    render :edit
  end

  def destroy
    track = Track.find_by(id: params[:id])

    track.destroy
  end

  private
  def track_params 
    params.require(:track).permit(:title, :ord, :lyrics, :track_type)
  end

  def set_album
    @album = Album.find(params[:album_id])
  end
end

w7d2/music/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :un_signed_in, only: [:new]
  def show
    @user = User.find_by(id: params[:id])
    if @user
      render :show
    else
      redirect_to :new
    end
  end

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      login!(@user)
      redirect_to user_url(@user)
    else
      :new
    end
  end

  def destroy
    user = User.find_by(id: params[:id])
    user.destroy
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

w7d2/music/app/helpers/albums_helper.rb
module AlbumsHelper
end

w7d2/music/app/helpers/bands_helper.rb
module BandsHelper
end

w7d2/music/app/helpers/tracks_helper.rb
module TracksHelper
end

w7d2/music/app/views/albums/index.html.erb
<div class="list-container">
<% @albums.each do |album| %>
  <ul class="any-list ">
    <li>
      <%= album.title %>
    </li>
    <li>
      <%= album.year %>
    </li>
    <li>
     <%=  album.band %>
    </li>
    <li> live: 
      <%= album.live %>
    </li>
  </ul>
<% end %>

</div>

w7d2/music/app/views/albums/new.html.erb
<div>
  <h1>Create a new album</h1>

  <form action="<%= band_albums_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label> Title
      <input type="text" name="album[title]">
    </label>

    <label> Year
      <input type="number" name="album[year]">
    </label>

    <p>Live: </p>
    <input type="radio" id="false" name="album[live]" value="false">
    <label for="false">False</label><br>
    <input type="radio" id="true" name="album[live]" value="true">
    <label for="true">True</label><br>

    <input type="submit" value="Create Album">
  </form>
</div>

w7d2/music/app/views/albums/show.html.erb
  
<h1>Album show page</h1>
<ul class="any-list ">
  <li>
    <%= @album.title %>
  </li>
  <li>
    <%= @album.year %>
  </li>
  <li>
    <%=  @album.band.name %>
  </li>
  <li> live: 
    <%= @album.live %>
  </li>

  <ol >
    <% @album.tracks.each do |track| %>
     <a href="<%= track_url(track) %>"><li>  <%= track.title %>  </li></a> 
    <% end %>
  </ol>
</ul>

<a href="<%= new_album_track_url(@album) %>">add track</a>
<a href="<%= band_url(@album.band_id) %>">Back to Band</a>

w7d2/music/app/views/bands/edit.html.erb
<div>
  <h1>Edit a Band</h1>

  <form action="<%= bands_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label> Name:
      <input type="text" name="band[name]">
    </label>

    <input type="submit" value="Update Band">
  </form>
</div>

w7d2/music/app/views/bands/index.html.erb
<div class="band-index">
    <% @bands.each do |band| %>
        <h1> 
        <a href="<%= band_url(band) %>">
            <%= band.name %> 
            </a>
        </h1> 
    <% end %>
</div>

w7d2/music/app/views/bands/new.html.erb
<div>
  <h1>Create a Band</h1>

  <form action="<%= bands_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label> Name:
      <input type="text" name="band[name]">
    </label>

    <input type="submit" value="Create Band">
  </form>
</div>

w7d2/music/app/views/bands/show.html.erb
<h2>Band show page</h2>
<p><%= @band.name %></p>

<h2>Albums</h2>
<div class="list-container">
<% @band.albums.each do |album| %>
  <ul class="any-list">
   <a href="<%= album_url(album) %>"> <li><%= album.title %></li> </a>
    <li><%= album.year %></li>
    <li><%= album.live %></li>
  </ul>
  <br>
<% end %>

</div>
<a href="<%= new_band_album_url(band_id: @band.id) %>">Create an album</a>



<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="DELETE">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
  <input type="submit" value="Delete Band">
</form>

w7d2/music/app/views/tracks/edit.html.erb
<form action="<%= track_url(@track) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method"  value="PUT">

  <label>Title 
    <input type="text" name="track[title]" value="<%= @track.title %>">
  </label>
  <label>Track number
    <input type="number" name="track[ord]" value="<%= @track.ord %>">
  </label>
  <label for="lyrics"></label>
  <textarea name="track[lyrics]" id="lyrics" cols="30" rows="10"> <%= @track.lyrics %>"</textarea>

   <p>Track type: </p>
    <input type="radio" id="regular" name="track[track_type]" value="regular" checked >
    <label for="regular">Regular</label><br>

    <input type="radio" id="bonus" name="track[track_type]" value="bonus">
    <label for="bonus">Bonus</label><br>


  <input type="submit" value="Edit Track">

</form>

w7d2/music/app/views/tracks/new.html.erb
<form action="<%= album_tracks_url %>" method="POST">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title 
    <input type="text" name="track[title]">
  </label>
  <label>Track number
    <input type="number" name="track[ord]">
  </label>
  <label for="lyrics"></label>
  <textarea name="track[lyrics]" id="lyrics" cols="30" rows="10"></textarea>

   <p>Track type: </p>
    <input type="radio" id="regular" name="track[track_type]" value="regular" checked >
    <label for="regular">Regular</label><br>

    <input type="radio" id="bonus" name="track[track_type]" value="bonus">
    <label for="bonus">Bonus</label><br>


  <input type="submit" value="Create Track">

</form>

w7d2/music/app/views/tracks/show.html.erb
<div>
  Title: <%= @track.title %><br>
  Album: <%= @track.album.title %><br>
  Track Number <%= @track.ord %><br>
  Track Type<%= @track.track_type %><br>
  Lyrics <%= @track.lyrics %><br>
</div>

<a href="<%= edit_track_url %>">edit track</a>
<a href="<%= album_url(@track.album) %>">Back to album</a>